# Command to run Telnet
# docker run -it --rm \
#	--log-driver none \
#	bernljung/telnet "$@"
#
FROM alpine:latest
LABEL maintainer "Jimmy Bernljung <jimmy.bernljung@gmail.com>"

ENTRYPOINT [ "telnet" ]