# docker run -it --rm \
#	--log-driver none \
# -v $PWD:/mnt \
# -w /mnt \
#	bernljung/wget "$@"
#
FROM alpine:latest
LABEL maintainer "Jimmy Bernljung <jimmy.bernljung@gmail.com>"

ENTRYPOINT [ "wget" ]