# docker run -it --rm \
# -v $HOME:$HOME \
# -v $PWD:$PWD \
# -w $PWD \
# -v /usr/local/lib/npm-global:/usr/local/lib/npm-global \
# -v $dockerfile_dir/docker_bridge_hosts:/etc/hosts \
# $NODE_IMAGE node "${args[@]}"
